##############################################################################
##############################################################################
###
### Running command:
###
###   /home/biocbuild/bbs-3.17-bioc/R/bin/R CMD build --keep-empty-dirs --no-resave-data pareg
###
##############################################################################
##############################################################################


* checking for file ‘pareg/DESCRIPTION’ ... OK
* preparing ‘pareg’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘pareg.Rmd’ using rmarkdown
The magick package is required to crop "/tmp/Rtmpkqlk4y/Rbuild152a744b3c1ea4/pareg/vignettes/pareg_files/figure-html/unnamed-chunk-4-1.png" but not available.
The magick package is required to crop "/tmp/Rtmpkqlk4y/Rbuild152a744b3c1ea4/pareg/vignettes/pareg_files/figure-html/unnamed-chunk-5-1.png" but not available.
/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.10/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
Quitting from lines 145-150 (pareg.Rmd) 
Error: processing vignette 'pareg.Rmd' failed with diagnostics:
Python module tensorflow_probability was not found.

Detected Python configuration:



--- failed re-building ‘pareg.Rmd’

--- re-building ‘pathway_similarities.Rmd’ using rmarkdown
The magick package is required to crop "/tmp/Rtmpkqlk4y/Rbuild152a744b3c1ea4/pareg/vignettes/pathway_similarities_files/figure-html/unnamed-chunk-2-1.png" but not available.
The magick package is required to crop "/tmp/Rtmpkqlk4y/Rbuild152a744b3c1ea4/pareg/vignettes/pathway_similarities_files/figure-html/unnamed-chunk-3-1.png" but not available.
--- finished re-building ‘pathway_similarities.Rmd’

SUMMARY: processing the following file failed:
  ‘pareg.Rmd’

Error: Vignette re-building failed.
Execution halted
